// Arabic-first titles for RTL; a missing slug falls back to the English name.

import type { Locale } from './i18n';

export const COMPONENT_NAME_AR: Record<string, string> = {
  button: 'زر',
  'floating-button': 'زر عائم',
  link: 'رابط',
  toggle: 'زر تبديل',
  'content-switcher': 'مبدّل المحتوى',
  'text-input': 'حقل نصّي',
  textarea: 'منطقة نصّية',
  'number-input': 'حقل رقمي',
  select: 'قائمة اختيار',
  dropdown: 'قائمة منسدلة',
  checkbox: 'مربّع اختيار',
  radio: 'زر اختيار',
  switch: 'مفتاح تبديل',
  slider: 'شريط تمرير',
  rating: 'تقييم',
  'input-otp': 'رمز تحقّق',
  'tag-input': 'حقل الوسوم',
  'search-box': 'مربّع بحث',
  'file-upload': 'رفع الملفّات',
  'date-picker': 'منتقي التاريخ',
  'date-range-picker': 'منتقي نطاق التاريخ',
  chip: 'شريحة',
  card: 'بطاقة',
  tag: 'وسم',
  'status-tag': 'وسم الحالة',
  avatar: 'صورة رمزية',
  divider: 'فاصل',
  'description-list': 'قائمة وصف',
  list: 'قائمة',
  'structured-list': 'قائمة مُنظّمة',
  metric: 'مؤشّر أداء',
  quote: 'اقتباس',
  timeline: 'مخطّط زمني',
  table: 'جدول',
  'aspect-ratio': 'نسبة الأبعاد',
  'digital-stamp': 'ختم رقمي',
  'code-snippet': 'مقتطف code',
  'saudi-riyal': 'الريال السعودي',
  charts: 'مخطّطات',
  'inline-alert': 'تنبيه مضمّن',
  notification: 'إشعار',
  'notification-toast': 'إشعار منبثق',
  tooltip: 'تلميح',
  spinner: 'مؤشّر تحميل',
  skeleton: 'هيكل تحميل',
  progress: 'مؤشّر تقدّم',
  'empty-state': 'حالة فارغة',
  modal: 'نافذة حوار',
  drawer: 'لوح جانبي',
  popover: 'لوح منبثق',
  'slideout-menu': 'قائمة منزلقة',
  'dropdown-menu': 'قائمة إجراءات',
  menubar: 'شريط قوائم',
  filtration: 'لوح تصفية',
  command: 'لوحة أوامر',
  tabs: 'تبويبات',
  breadcrumb: 'مسار تنقّل',
  pagination: 'ترقيم صفحات',
  accordion: 'أكورديون',
  'progress-indicator': 'مؤشّر خطوات',
  collapsible: 'عنصر قابل للطي',
  'scroll-area': 'منطقة تمرير',
  carousel: 'معرض متحرّك',
  sidebar: 'شريط جانبي',
  'dga-provider': 'المزوّد',
};

export function componentName(slug: string, apiName: string, locale: Locale): string {
  return locale === 'ar' ? (COMPONENT_NAME_AR[slug] ?? apiName) : apiName;
}
