
import type { Locale } from './i18n';

export const EXAMPLE_TITLE_AR: Record<string, string> = {
  'Arabic (RTL)': 'العربية (RTL)',
  Basic: 'أساسي',
  Variants: 'الأنماط',
  Sizes: 'الأحجام',
  Tones: 'الدرجات',
  'Arabic label': 'تسمية عربية',
  'Arabic labels': 'تسميات عربية',
  'Required & error states': 'الإلزام وحالات الخطأ',
  'With icons': 'مع أيقونات',
  'Semantic types': 'الأنواع الدلالية',
  'Hijri calendar (Arabic)': 'التقويم الهجري',
  'Fill styles': 'أنماط التعبئة',
  'As a link (asChild)': 'كرابط (asChild)',
  'As a link': 'كرابط',
  Amount: 'المبلغ',
  'Negative and written values': 'القيم السالبة والمكتوبة',
  Numerals: 'الأرقام',
  'The symbol': 'الرمز',
  'Inline in text': 'ضمن النص',

  'With leading icons': 'مع أيقونات في المقدّمة',
  'With icon': 'مع أيقونة',
  'With custom icon': 'مع أيقونة مخصّصة',
  'With a trend chart': 'مع مخطط اتجاه',
  'With arrow': 'مع سهم',
  'With an avatar': 'مع صورة رمزية',
  'With actions (undo)': 'مع إجراءات (تراجع)',
  'With actions': 'مع إجراءات',
  'With a chevron': 'مع سهم إشارة',
  'White surface (Arabic)': 'سطح أبيض',
  'Vertical with a rich value': 'عمودي بقيمة غنيّة',
  'Vertical steps': 'خطوات عمودية',
  Vertical: 'عمودي',
  'Verification code': 'رمز التحقق',
  'Verification bar': 'شريط التحقق',
  'Validation & rejections': 'التحقق والرفض',
  'Validated email recipients': 'مستلمو بريد مُتحقَّق منهم',
  'Update in place (Arabic)': 'تحديث في المكان',
  'Title, quote & author': 'العنوان والاقتباس والمؤلّف',
  'Title, icon & inverted surface': 'العنوان والأيقونة وسطح معكوس',
  'Switching content': 'تبديل المحتوى',
  'Sub-menus, trailing slots & groups': 'قوائم فرعية وفتحات نهائية ومجموعات',
  'Styles (icon-only)': 'الأنماط (أيقونة فقط)',
  'Status styles': 'أنماط الحالة',
  Statuses: 'الحالات',
  'Static pager': 'مُرقّم ثابت',
  States: 'الحالات',
  'Stateful pager with paginationRange': 'مُرقّم متغيّر الحالة مع paginationRange',
  'Standalone with a trailing icon (RTL-aware)': 'مستقل بأيقونة نهائية',
  'Sortable columns': 'أعمدة قابلة للفرز',
  'Small and disabled': 'صغير ومعطّل',
  'Sizes, styles & indeterminate': 'الأحجام والأنماط والحالة غير المحدّدة',
  'Sizes (Arabic)': 'الأحجام',
  'Sizes and shapes': 'الأحجام والأشكال',
  'Sizes and shape': 'الأحجام والشكل',
  'Single value with readout': 'قيمة مفردة مع عرض',
  'Single select': 'اختيار مفرد',
  'Single language, no line numbers': 'لغة واحدة، بلا أرقام أسطر',
  'Single file (button variant)': 'ملف واحد (نمط الزر)',
  'Single choice': 'اختيار واحد',
  Shapes: 'الأشكال',
  'Setting toggle': 'مفتاح إعداد',
  'Settings drawer': 'لوح الإعدادات',
  'Semantic variants': 'الأنماط الدلالية',
  'Selectable rows (controlled)': 'صفوف قابلة للاختيار (مُتحكَّم بها)',
  'Selectable rows': 'صفوف قابلة للاختيار',
  Searchable: 'قابل للبحث',
  'RTL with Arabic': 'RTL مع العربية',
  'Rounded (Arabic)': 'دائري',
  'Review summary': 'ملخّص المراجعة',
  'Required & error': 'الإلزام والخطأ',
  'Read-only average': 'متوسّط للقراءة فقط',
  'Rate a service': 'قيّم خدمة',
  'Range (two thumbs)': 'نطاق (مقبضان)',
  'Radio group': 'مجموعة أزرار اختيار',
  Quantity: 'الكمية',
  'Presets (composition recipe)': 'إعدادات جاهزة (وصفة تركيب)',
  'Pie chart': 'مخطط دائري',
  'Percentage format': 'صيغة النسبة المئوية',
  'Overlay filter (controlled)': 'تصفية منبثقة (مُتحكَّم بها)',
  'Outline triggers (Arabic)': 'مشغّلات محدّدة',
  'Order history': 'سجل الطلبات',
  'Open by default': 'مفتوح افتراضيًا',
  'On by default, with a hint': 'مُفعّل افتراضيًا، مع تلميح',
  'On an image (asChild)': 'على صورة (asChild)',
  'On a dark surface (Arabic)': 'على سطح داكن',
  'On a colored surface': 'على سطح ملوّن',
  'No data': 'لا بيانات',
  'Nesting levels and tone': 'مستويات التداخل والدرجة',
  'Multi-select': 'اختيار متعدّد',
  'Multiple open': 'عدّة مفتوحة',
  'Multiple languages': 'لغات متعدّدة',
  'Minimal table': 'جدول مبسّط',
  'Message field': 'حقل رسالة',
  'Masked PIN': 'PIN مُقنّع',
  'Markers with icons': 'علامات بأيقونات',
  'Live filtering (controlled)': 'تصفية حيّة (مُتحكَّم بها)',
  'Line chart': 'مخطط خطّي',
  'Linear bar': 'شريط خطّي',
  'Label, value, change': 'التسمية والقيمة والتغيّر',
  'Labelled field': 'حقل بتسمية',
  'Labeled toggle': 'مفتاح بتسمية',
  Labeled: 'بتسمية',
  '⌘K dialog': 'حوار ⌘K',
  'In-text links': 'روابط داخل النص',
  'Inline placeholder': 'عنصر نائب مضمّن',
  'Inline panel (Arabic)': 'لوح مضمّن',
  'Inline palette': 'لوحة مضمّنة',
  'Inline edit form (Arabic)': 'نموذج تحرير مضمّن',
  'Inline command': 'أمر مضمّن',
  'Inherits size & color': 'يرث الحجم واللون',
  'In-field prefix & suffix': 'بادئة ولاحقة داخل الحقل',
  'Image with fallback': 'صورة مع بديل',
  'Icons & loading': 'الأيقونات والتحميل',
  'Icon-only toggles': 'مفاتيح بأيقونة فقط',
  'Horizontal with helper text': 'أفقي مع نص مساعد',
  'Horizontal steps': 'خطوات أفقية',
  'Horizontal and vertical': 'أفقي وعمودي',
  Horizontal: 'أفقي',
  'Help icon': 'أيقونة مساعدة',
  'Half-star precision': 'دقّة نصف نجمة',
  'Group with overflow': 'مجموعة مع فائض',
  'Grouped options': 'خيارات مجمّعة',
  'Grouped navigation': 'تنقّل مجمّع',
  Grouped: 'مجمّع',
  'Full-width': 'عرض كامل',
  'Full card with icon, action & footer': 'بطاقة كاملة بأيقونة وإجراء وتذييل',
  'Filter form (Arabic)': 'نموذج تصفية',
  'Filter bar (controlled)': 'شريط تصفية (مُتحكَّم به)',
  'Fill styles & fixed height': 'أنماط التعبئة وارتفاع ثابت',
  'File / Edit / View': 'ملف / تحرير / عرض',
  'Feedback states': 'حالات التغذية الراجعة',
  'FAQ (single)': 'الأسئلة الشائعة (مفرد)',
  'External link': 'رابط خارجي',
  'Extended pill (icon + label)': 'حبّة ممتدة (أيقونة + تسمية)',
  'Expanded explainer': 'شرح موسّع',
  'Error & no steppers': 'خطأ وبلا أزرار زيادة',
  'Educational extension': 'امتداد تعليمي',
  'Drag-and-drop zone': 'منطقة سحب وإفلات',
  Dots: 'نقاط',
  'Dot appearance': 'مظهر النقطة',
  'Dismissible (Arabic)': 'قابل للإغلاق',
  'Default value, helper & a disabled option': 'قيمة افتراضية ونص مساعد وخيار معطّل',
  Default: 'افتراضي',
  'Decimal step & subtle steppers': 'خطوة عشرية وأزرار خفيّة',
  'Dashboard grid (MetricGroup)': 'شبكة لوحة (MetricGroup)',
  'Dark mode': 'الوضع الداكن',
  'Custom shortcut (Arabic)': 'اختصار مخصّص',
  'Custom separator': 'فاصل مخصّص',
  'Current-page links': 'روابط الصفحة الحالية',
  'Country picker': 'منتقي الدولة',
  'Controlled with readout': 'مُتحكَّم به مع عرض',
  'Controlled tags': 'وسوم مُتحكَّم بها',
  'Consent checkbox': 'مربّع موافقة',
  'Confirmation dialog': 'حوار تأكيد',
  'Composed parts': 'أجزاء مركّبة',
  'Composed cells': 'خلايا مركّبة',
  'Compact, no dividers': 'مضغوط، بلا فواصل',
  'Common ratios': 'نسب شائعة',
  'Colored fallbacks with status': 'بدائل ملوّنة مع حالة',
  'Collapsible with Show More': 'قابل للطي مع «عرض المزيد»',
  'Collapsed middle': 'طيّ الوسط',
  'Circular states (Arabic)': 'حالات دائرية',
  'Circular ring': 'حلقة دائرية',
  'Checkbox items': 'عناصر مربّعات اختيار',
  'Checkboxes & radio group': 'مربّعات اختيار ومجموعة أزرار',
  'Card placeholder': 'عنصر نائب لبطاقة',
  'Capped at three': 'بحدٍّ أقصى ثلاثة',
  'Brand theme': 'سمة العلامة',
  'Bounded with helper text': 'محدود مع نص مساعد',
  'Bounded range': 'نطاق محدود',
  'Bottom sheet': 'لوح سفلي',
  'Both axes': 'كلا المحورين',
  'Basic trail': 'مسار أساسي',
  'Basic tabs': 'تبويبات أساسية',
  'Basic search': 'بحث أساسي',
  'Basic list': 'قائمة أساسية',
  'Basic card': 'بطاقة أساسية',
  'Bar chart': 'مخطط أعمدة',
  'Arrows, dots, and loop': 'أسهم ونقاط وتكرار',
  Arrows: 'أسهم',
  'Arabic, required with an error': 'عربي، إلزامي مع خطأ',
  'App shell': 'هيكل التطبيق',
  'Activity feed (with Avatar)': 'موجز نشاط (مع صورة رمزية)',
  'Actions & dismissible': 'إجراءات وقابل للإغلاق',
  'Account menu': 'قائمة الحساب',
  '16 / 9 box': 'صندوق 16 / 9',
};

export function exampleTitle(title: string, locale: Locale): string {
  return locale === 'ar' ? (EXAMPLE_TITLE_AR[title] ?? title) : title;
}
