#!/usr/bin/env node
// gen-tokens - derives the editable token list from the installed @dev-dga/css :root
// into src/lib/tokens.generated.ts.

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const cssFile = join(root, 'node_modules/@dev-dga/css/dist/index.css');
const outFile = join(root, 'src/lib/tokens.generated.ts');

const css = readFileSync(cssFile, 'utf8');

const m = css.match(/:root\{([^}]*)\}/);
if (!m) {
  console.error('[gen-tokens] could not find :root{} in', cssFile);
  process.exit(1);
}
const decls = [...m[1].matchAll(/(--ddga-[a-z0-9-]+)\s*:\s*([^;]+)/g)].map((d) => ({
  name: d[1],
  value: d[2].trim(),
}));

function kindFor(name, v) {
  if (name.startsWith('--ddga-font-weight-')) return 'weight';
  if (name.startsWith('--ddga-shadow-')) return 'shadow';
  const s = v.trim();
  // <input type=color> only accepts #rgb / #rrggbb - use a picker for those.
  if (/^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(s)) return 'color';
  if (
    /^#([0-9a-fA-F]{4}|[0-9a-fA-F]{8})$/.test(s) ||
    /^(rgba?|hsla?)\(/i.test(s) ||
    ['transparent', 'currentcolor', 'white', 'black'].includes(s.toLowerCase())
  )
    return 'colorText';
  if (/^-?\d*\.?\d+(px|rem|em)$/.test(s)) return 'length';
  if (/^-?\d*\.?\d+$/.test(s)) return 'number';
  return 'text';
}

const GROUPS = [
  ['semantic', 'theme', (n) => n.startsWith('--ddga-color-')],
  ['textColors', 'theme', (n) => n.startsWith('--ddga-text-')],
  ['brandRamp', 'brand', (n) => n.startsWith('--ddga-brand-')],
  ['radius', 'foundation', (n) => n.startsWith('--ddga-radius-')],
  ['spacing', 'foundation', (n) => n.startsWith('--ddga-space-') || n.startsWith('--ddga-card-')],
  ['typography', 'foundation', (n) => n.startsWith('--ddga-font-')],
  ['shadow', 'foundation', (n) => n.startsWith('--ddga-shadow-')],
  ['saScale', 'primitive', (n) => n.startsWith('--ddga-sa-')],
  ['gray', 'primitive', (n) => n.startsWith('--ddga-gray-')],
  ['success', 'primitive', (n) => n.startsWith('--ddga-success-')],
  ['warning', 'primitive', (n) => n.startsWith('--ddga-warning-')],
  ['error', 'primitive', (n) => n.startsWith('--ddga-error-')],
  ['info', 'primitive', (n) => n.startsWith('--ddga-info-')],
  ['gold', 'primitive', (n) => n.startsWith('--ddga-gold-')],
  ['lavender', 'primitive', (n) => n.startsWith('--ddga-lavender-')],
  ['chart', 'primitive', (n) => n.startsWith('--ddga-chart-')],
  ['alpha', 'primitive', (n) => n.startsWith('--ddga-alpha-')],
];

const groupOf = (name) => GROUPS.find(([, , test]) => test(name)) ?? ['other', 'primitive'];

const buckets = new Map();
const tierOf = new Map();
for (const [key, tier] of GROUPS) {
  buckets.set(key, []);
  tierOf.set(key, tier);
}
buckets.set('other', []);
tierOf.set('other', 'primitive');
for (const d of decls) {
  const [key] = groupOf(d.name);
  buckets.get(key).push({ name: d.name, value: d.value, kind: kindFor(d.name, d.value) });
}

const SKIP_GROUPS = new Set(['gold', 'lavender']);

const groups = [...buckets.entries()]
  .filter(([key, tokens]) => tokens.length > 0 && !SKIP_GROUPS.has(key))
  .map(([key, tokens]) => ({ key, tier: tierOf.get(key), tokens }));

const banner =
  '// AUTO-GENERATED by scripts/gen-tokens.mjs from @dev-dga/css :root.\n' +
  '// Do not edit by hand - run `pnpm gen` (or dev/build/typecheck) to regenerate.\n';

const body =
  `export type TokenKind =\n  | 'color'\n  | 'colorText'\n  | 'length'\n  | 'number'\n  | 'text'\n  | 'weight'\n  | 'shadow';\n` +
  `export interface Token {\n  name: string;\n  value: string;\n  kind: TokenKind;\n}\n` +
  `export type TokenTier = 'theme' | 'brand' | 'foundation' | 'primitive';\n` +
  `export interface TokenGroup {\n  key: string;\n  tier: TokenTier;\n  tokens: Token[];\n}\n\n` +
  `export const TOKEN_COUNT = ${groups.reduce((n, g) => n + g.tokens.length, 0)};\n\n` +
  `export const TOKEN_GROUPS: TokenGroup[] = ${JSON.stringify(groups, null, 2)};\n`;

writeFileSync(outFile, banner + '\n' + body);
console.log(
  `[gen-tokens] ${decls.length} tokens -> ${groups.length} groups -> src/lib/tokens.generated.ts`,
);
