// gen-demos - copies each ## Example tsx fence from content/ into demos/.generated/ and
// writes the demo registries (registry.generated.ts + ar-meta.generated.ts).

import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const contentDir = join(root, 'content', 'components');
const arDir = join(root, 'content', 'i18n');
const genDir = join(root, 'demos', '.generated');
const registryPath = join(root, 'demos', 'registry.generated.ts');
const arMetaPath = join(root, 'content', 'ar-meta.generated.ts');

function stripFrontmatter(md) {
  const m = md.match(/^---\n[\s\S]*?\n---\n?/);
  return m ? md.slice(m[0].length) : md;
}

// Must mirror src/lib/content.ts parseBody so demo indexes match the app's example indexes.
export function parseExamples(md) {
  const body = stripFrontmatter(md);
  const sectionRe = /^##\s*Example:?\s*(.*)$/gim;
  const headings = [];
  let m;
  while ((m = sectionRe.exec(body)) !== null) {
    headings.push({ title: (m[1] || '').trim(), index: m.index });
  }
  const examples = [];
  headings.forEach((h, i) => {
    const end = i + 1 < headings.length ? headings[i + 1].index : body.length;
    const fence = body.slice(h.index, end).match(/```tsx\n([\s\S]*?)\n```/);
    if (fence) examples.push({ title: h.title || `Example ${i + 1}`, code: fence[1] });
  });
  return examples;
}

function writeModule(modPath, code) {
  writeFileSync(modPath, code.endsWith('\n') ? code : code + '\n');
}

function main() {
  rmSync(genDir, { recursive: true, force: true });
  mkdirSync(genDir, { recursive: true });

  const files = existsSync(contentDir)
    ? readdirSync(contentDir)
        .filter((f) => f.endsWith('.md'))
        .sort()
    : [];

  const enEntries = [];
  const arEntries = [];
  const arCodeEntries = [];
  let exampleCount = 0;
  let arCount = 0;

  for (const file of files) {
    const slug = file.replace(/\.md$/, '');
    const examples = parseExamples(readFileSync(join(contentDir, file), 'utf8'));
    if (examples.length === 0) continue;

    const slugDir = join(genDir, slug);
    mkdirSync(slugDir, { recursive: true });

    const enImports = examples.map((ex, i) => {
      writeModule(join(slugDir, `${i}.tsx`), ex.code);
      exampleCount++;
      return `lazy(() => import('./.generated/${slug}/${i}'))`;
    });
    enEntries.push(`  ${JSON.stringify(slug)}: [\n    ${enImports.join(',\n    ')},\n  ],`);

    const arFile = join(arDir, `${slug}.ar.md`);
    if (!existsSync(arFile)) continue;
    const arExamples = parseExamples(readFileSync(arFile, 'utf8'));
    if (arExamples.length === 0) continue;

    const arByTitle = new Map(arExamples.map((ex) => [ex.title, ex.code]));
    let matched = 0;
    const arImports = examples.map((ex, i) => {
      const code = arByTitle.get(ex.title);
      if (code == null) return 'null';
      mkdirSync(join(slugDir, 'ar'), { recursive: true });
      writeModule(join(slugDir, 'ar', `${i}.tsx`), code);
      matched++;
      arCount++;
      return `lazy(() => import('./.generated/${slug}/ar/${i}'))`;
    });
    if (matched === 0) continue;

    arEntries.push(`  ${JSON.stringify(slug)}: [\n    ${arImports.join(',\n    ')},\n  ],`);
    const arCodes = examples.map((ex) => {
      const code = arByTitle.get(ex.title);
      return code == null ? 'null' : JSON.stringify(code);
    });
    arCodeEntries.push(`  ${JSON.stringify(slug)}: [\n    ${arCodes.join(',\n    ')},\n  ],`);
  }

  const registry = `// AUTO-GENERATED by scripts/gen-demos.mjs - do not edit.
import { lazy, type ComponentType, type LazyExoticComponent } from 'react';

export const demoRegistry: Record<string, LazyExoticComponent<ComponentType>[]> = {
${enEntries.join('\n')}
};

// Arabic demo variants, aligned to the English example index (null = fall back
// to the English demo). Only components with at least one variant appear here.
export const arDemoRegistry: Record<string, (LazyExoticComponent<ComponentType> | null)[]> = {
${arEntries.join('\n')}
};
`;
  writeFileSync(registryPath, registry);

  const arBlurbEntries = [];
  if (existsSync(arDir)) {
    for (const file of readdirSync(arDir)
      .filter((f) => f.endsWith('.ar.md'))
      .sort()) {
      const slug = file.replace(/\.ar\.md$/, '');
      const raw = readFileSync(join(arDir, file), 'utf8');
      const fm = raw.match(/^---\n([\s\S]*?)\n---/);
      const desc = fm && fm[1].match(/^description:\s*(?:'([^']*)'|"([^"]*)"|(.*))$/m);
      const value = desc ? (desc[1] ?? desc[2] ?? desc[3] ?? '').trim() : '';
      if (value) arBlurbEntries.push(`  ${JSON.stringify(slug)}: ${JSON.stringify(value)},`);
    }
  }
  const arMeta = `// AUTO-GENERATED by scripts/gen-demos.mjs - do not edit.
export const arBlurbs: Record<string, string> = {
${arBlurbEntries.join('\n')}
};

// Arabic source for the shown code block, aligned to the English example index.
export const arExampleCode: Record<string, (string | null)[]> = {
${arCodeEntries.join('\n')}
};
`;
  writeFileSync(arMetaPath, arMeta);

  console.log(
    `[gen-demos] ${files.length} content file(s) → ${enEntries.length} components, ${exampleCount} examples · ${arBlurbEntries.length} ar blurbs · ${arCount} ar examples`,
  );
}

main();
